### ISSUE TITLE
storybook/addon-info compatibility

### ISSUE THREAD

**Issue by tkiethanom** [dump247/storybook-state#5]
I'm trying to get this to work with storybook/addon-info but with no luck. 

`withState({ value: '' }, store =>
        withInfo('some text')(
            <Component> ...,
        ),
    ),`

`Invariant Violation: StoryState.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by dump247** [comment]
Looks like this is the same issue from #4.

I just released v1.3.0 that should resolve the issue.

**Comment by tkiethanom** [comment]
For anyone wondering, the correct way to use addon-info and storybook-state together should be like the following. Don't forget the extra `()` after `withInfo()`.

```js
storiesOf('Component', module).add(
    'storyname',
    withState({ value: '' }, store =>
        withInfo('some text')(() => (
             <Component />
        ))(),
    ),
);
```

**Comment by JoshuaMorris** [comment]
@tkiethanom  this didn’t solve the issue for me using v1.3.0

**Comment by tkiethanom** [comment]
@JoshuaMorris are you getting the same Invariant Violation error as I was getting before?

**Comment by Jessica-Koch** [comment]
I was able to get this to work for me with the `withInfo` and the chapters plugin...

```
storiesOf('Component', module).add(
  'storyname',
   withState({value: ''})(
      withInfo('some text')(({store}) => (
         <Component />
))) )
```

**Comment by MalcolmDwyer** [comment]
Just to help out anyone with the same issue I had. If I had stories defined for only one component, there was no problem... but as soon as I added a second 'storiesOf('otherComponent')' in the mix then withState(withInfo()) broke for me (on the first component).

I was doing this:
```
withState({value: ''})(({store}) =>  // DON'T PUT {store} HERE!!! 
      withInfo(
        'stuff'
      )(() => (
        <MyComponent ...
```
Which resulted in the error:
```
Cannot read property 'story' of null
TypeError: Cannot read property 'story' of null
```
pointing to this line in the webpacked trace:
```
value: function _getComponentDescription() {
   ...
   if (STORYBOOK_REACT_CLASSES[key].name === _this3.props.context.story) {
```

Moving the `{store}` argument into the inner `withInfo` function call (as @Jessica-Koch shows above) fixed this issue. :tada:

@dump247 If you understand the above and have a fix for passing the `{store}` through from above, that would be nice.  It was a hard issue to track down. (Since it only occurred when I added the second component, and the error message was unrelated to my code).

**Comment by dump247** [comment]
@MalcolmDwyer  I think your issue is that you are invoking things incorrectly.

It should work like this:
```javascript
withState({ value: '' })(
  withInfo('stuff')(
    ({ store }) => <MyComponent.../>
  )
)
```
It does seem a bit awkward, but this should make it work. This is just how  you have to chain storybook plugins.

Take a look here for a working example: https://github.com/dump247/storybook-state/blob/master/.storybook/config.js#L16-L21

~It seems like adding an example of how to do this in the readme would be a good improvement.~ There is! https://github.com/dump247/storybook-state/#extension

**Comment by MalcolmDwyer** [comment]
@dump247 Thanks. I had figured out the solution to my error.  My point (in the note to you at the end) was that this is probably a common mistake, and the error message you get if you do it wrong provides no hint what is wrong.  getComponentDescription() tries to read this.props.context.story, but context is null when you try to pass `{store}` to withState() (as you normally would)... so you just get a red page with a generic storybook error.  If I'm understanding correctly... there could be a check added to the storybook-state code at that point that would provide a more helpful result. Thanks again

**Comment by dump247** [comment]
@MalcolmDwyer I see. That does make sense and I appreciate your clarification.

The `store` variable is passed through by storybook as context, which itself is an undocumented feature AFAIK. I am not sure how to trap or detect that particular error.

**Comment by dgana** [comment]
Thanks @dump247 works perfectly chain with info after.

But now i just got a warning of deprecation `Passing stories directly into withInfo() is deprecated, instead use addDecorator(withInfo) and pass options with the 'info' parameter`

`"@storybook/react": "4.1.11"`
`"@dump247/storybook-state": "1.5.2"`
`"@storybook/addon-info": "4.1.12"`
